apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  DB_USERNAME: {{ .Values.secret.DB_USERNAME | b64enc }}
  DB_PASSWORD: {{ .Values.secret.DB_PASSWORD | b64enc }}
